### PR TITLE
3 core matchers

### PR DESCRIPTION
**Pull request by Graur**
Introduce Core matchers: `.is`,  `.anything ` and `described-as` objects

### CODE REVIEW

**Comment by yegor256** [comment]
@Graur looks good

**Comment by Graur** [comment]
tkank you!

**Comment by 0pdd** [comment]
@Graur the puzzle [#60](https://github.com/objectionary/eo-hamcrest/issues/60) is still not solved.

**Comment by 0pdd** [comment]
@Graur the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@Graur the only puzzle [#60](https://github.com/objectionary/eo-hamcrest/issues/60) is solved here.

**Pull request merged**
